performance health check here

diff --git a/.github/workflows/admin-portal.stage.yml b/.github/workflows/admin-portal.stage.yml
--- a/.github/workflows/admin-portal.stage.yml
+++ b/.github/workflows/admin-portal.stage.yml
@@ -3,7 +3,7 @@ name: Deploy Admin Portal (Stage)
 on:
   push:
     branches:
-      - 'main'
+      - 'devops-verify-health-docker-before-deploy'
     paths:
       - 'apps/admin-portal/**'
 
@@ -14,7 +14,8 @@ env:
   DOCKERFILE_PATH: apps/admin-portal/Dockerfile
   DOCKER_COMPOSE_PATH: apps/admin-portal/docker-compose.yml
   ENV_FILE_PATH: apps/admin-portal/.env
-  DOCKER_MAP_PORT: 3001:3001
+  DOCKER_HOST_PORT: 3001 # Change this value if your server is already run docker container with this port, using command docker ps to check it
+  DOCKER_CONTAINER_PORT: 3001 # This is the app port, which command yarn start run and provided
 
 jobs:
   build-and-deploy:
@@ -36,6 +37,32 @@ jobs:
           docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.APP_NAME }} .
           docker save -o ${{ env.APP_NAME }}.tar ${{ env.APP_NAME }}
 
+      - name: Test Docker container run
+        run: |
+          # Run the new container temporarily
+          docker run -d --name ${{ env.APP_NAME }}_test \
+          --health-cmd="curl -f http://localhost:${{ env.DOCKER_CONTAINER_PORT}} || exit 1" \
+          --health-interval=10s \
+          --health-timeout=5s \
+          --health-retries=3 \
+          my-image:latest
+
+          # Wait for health check
+          sleep 30  # Adjust based on your health-check settings
+
+          # Check health status
+          HEALTH_STATUS=$(docker inspect --format='{{json .State.Health.Status}}' temp_test_container)
+
+          if [[ "$HEALTH_STATUS" == "\"healthy\"" ]]; then
+              echo "✅ New container is healthy. Replacing old container..."
+              docker stop old_container_name && docker rm old_container_name
+              docker run -d --name old_container_name my-image:latest
+          else
+              echo "❌ Error: New container is $HEALTH_STATUS. Cleaning up..."
+              docker stop temp_test_container && docker rm temp_test_container
+              exit 1
+          fi
+
       - name: Create docker-compose file
         run: |
           # Remove old docker-compose file if it exists
@@ -49,7 +76,7 @@ jobs:
               container_name: ${{ env.APP_NAME }}
               restart: always
               ports:
-                - "${{ env.DOCKER_MAP_PORT }}"
+                - "${{ env.DOCKER_HOST_PORT }}:${{ env.DOCKER_CONTAINER_PORT }}"
           EOF
 
       - name: Copy Docker image to ec2 use SSH Key
@@ -78,4 +105,4 @@ jobs:
             # Wait for 5 seconds to allow container to start
             sleep 5
             # Ping the application to verify it's running
-            curl -f http://localhost:${DOCKER_MAP_PORT#*:} || exit 1
+            curl -f http://localhost:${DOCKER_HOST_PORT} || exit 1
